# Generated by Django 5.0.2 on 2024-02-16 07:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOW',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None)),
            ],
        ),
    ]
