# Generated by Django 5.0.2 on 2024-02-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_sow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sow',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
