# Generated by Django 5.0.2 on 2024-02-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_sow_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sow',
            old_name='id',
            new_name='sow_id',
        ),
    ]
