# Generated by Django 5.0.2 on 2024-02-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_pdf_files_pdffiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf_Files',
        ),
    ]
